//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_GHAR_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VeggierhinoEntities : DbContext
    {
        public VeggierhinoEntities()
            : base("name=VeggierhinoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PA_DELIVERYBOY_DETAILS> PA_DELIVERYBOY_DETAILS { get; set; }
        public virtual DbSet<PA_MASTER_GENERAL> PA_MASTER_GENERAL { get; set; }
        public virtual DbSet<PA_MASTER_ITEM> PA_MASTER_ITEM { get; set; }
        public virtual DbSet<PA_MASTER_USER> PA_MASTER_USER { get; set; }
        public virtual DbSet<PA_MOB_APP_TOKEN_AUTH> PA_MOB_APP_TOKEN_AUTH { get; set; }
        public virtual DbSet<PA_MOB_CUST_SIGHN_UP> PA_MOB_CUST_SIGHN_UP { get; set; }
        public virtual DbSet<PA_ORDER_DETAILS> PA_ORDER_DETAILS { get; set; }
        public virtual DbSet<PA_ORDER_DETIAL_DESC> PA_ORDER_DETIAL_DESC { get; set; }
        public virtual DbSet<TEMP_PA_CART_DATA> TEMP_PA_CART_DATA { get; set; }
    }
}
