//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_GHAR_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PA_DELIVERYBOY_DETAILS
    {
        public int DELIVERYBOY_ID { get; set; }
        public string DELIVERYBOY_NAME { get; set; }
        public string MOBILENO { get; set; }
        public bool ISACTIVE { get; set; }
        public string PASSWORD { get; set; }
    }
}
