//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_GHAR_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PA_MASTER_USER
    {
        public string USERID { get; set; }
        public string USERNAME { get; set; }
        public string USERPASSWORD { get; set; }
        public string EMAILID { get; set; }
        public string MOBILENO { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
        public Nullable<bool> ISADMIN { get; set; }
    }
}
