//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_GHAR_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PA_MASTER_ITEM
    {
        public int ITEM_ID { get; set; }
        public string ITEM_NAME { get; set; }
        public string ITEM_DESCRIPTION { get; set; }
        public bool ISACTIVE { get; set; }
        public Nullable<decimal> ITEM_PRICE { get; set; }
        public byte[] ITEM_PHOTO { get; set; }
        public string ITEM_CATEGORY { get; set; }
        public string ITEM_UNIT { get; set; }
        public Nullable<decimal> ITEM_QUANTITY { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> ENTRYON { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEON { get; set; }
    }
}
