//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_GHAR_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PA_MOB_CUST_SIGHN_UP
    {
        public int CUST_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string EMAIL_ID { get; set; }
        public string MOBILE_NO { get; set; }
        public string PASSWORD { get; set; }
        public string C_ON { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
        public string ADDRESS { get; set; }
    }
}
