//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_GHAR_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PA_MOB_APP_TOKEN_AUTH
    {
        public int S_NO { get; set; }
        public string LOGIN_ID { get; set; }
        public string DEVICE_ID { get; set; }
        public string TOKEN { get; set; }
        public Nullable<System.DateTime> C_ON { get; set; }
        public Nullable<System.DateTime> U_ON { get; set; }
    }
}
