//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_GHAR_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PA_ORDER_DETIAL_DESC
    {
        public long SR_NO { get; set; }
        public string ORDER_ID { get; set; }
        public string ITEMID_ID { get; set; }
    }
}
