//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_GHAR_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_PA_CART_DATA
    {
        public int ID { get; set; }
        public string ITEM_ID { get; set; }
        public string QUANTITY { get; set; }
        public string CUSTOMER_ID { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
    }
}
